package fr.thomas.atomisation.init;

import com.google.common.collect.Lists;
import fr.thomas.atomisation.Atomisation;
import fr.thomas.atomisation.items.ItemAtomisation;
import fr.thomas.atomisation.items.ItemCustomAxe;
import fr.thomas.atomisation.items.ItemCustomPickaxe;
import net.minecraft.inventory.EquipmentSlotType;
import net.minecraft.item.*;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import java.util.List;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, modid = Atomisation.MODID)
public class ModItems {
    public static final ModItems INSTANCE = new ModItems();
    public static List<Item> items;
    public static Item accelerator;
    public static Item actinium225;
    public static Item actinium226;
    public static Item aluminium27;
    public static Item aluminium28;
    public static Item americium241;
    public static Item americium242;
    public static Item antimoine121;
    public static Item antimoine122;
    public static Item argent107;
    public static Item argent108;
    public static Item argent109;
    public static Item argent110;
    public static Item argon36;
    public static Item argon37;
    public static Item argon38;
    public static Item argon39;
    public static Item arsenic75;
    public static Item arsenic76;
    public static Item astate219;
    public static Item astate220;
    public static Item azote14;
    public static Item azote15;
    public static Item azote16;
    public static Item baryum134;
    public static Item baryum135;
    public static Item baryum136;
    public static Item baryum137;
    public static Item baryum138;
    public static Item baryum139;
    public static Item berkelium249;
    public static Item beryllium9;
    public static Item beryllium10;
    public static Item beta_minus;
    public static Item bismuth209;
    public static Item bismuth210;
    public static Item bohrium272;
    public static Item bore10;
    public static Item bore11;
    public static Item bore12;
    public static Item brome79;
    public static Item brome80;
    public static Item cadmium108;
    public static Item cadmium109;
    public static Item cadmium110;
    public static Item cadmium111;
    public static Item cadmium112;
    public static Item cadmium113;
    public static Item calcium40;
    public static Item calcium41;
    public static Item calcium42;
    public static Item calcium43;
    public static Item calcium44;
    public static Item calcium45;
    public static Item californium249;
    public static Item californium250;
    public static Item californium251;
    public static Item californium252;
    public static Item californium253;
    public static Item carbone12;
    public static Item carbone13;
    public static Item carbone14;
    public static Item cerium140;
    public static Item cerium141;
    public static Item cesium133;
    public static Item cesium134;
    public static Item chlore35;
    public static Item chlore36;
    public static Item chrome52;
    public static Item chrome53;
    public static Item chrome54;
    public static Item chrome55;
    public static Item cobalt59;
    public static Item cobalt60;
    public static Item copernicium283;
    public static Item copernicium284;
    public static Item cuivre63;
    public static Item cuivre64;
    public static Item curium242;
    public static Item curium243;
    public static Item curium244;
    public static Item curium245;
    public static Item curium246;
    public static Item curium247;
    public static Item curium248;
    public static Item curium249;
    public static Item darmstadtium277;
    public static Item darmstadtium279;
    public static Item darmstadtium281;
    public static Item disposable_fusionner;
    public static Item dubnium262;
    public static Item dubnium263;
    public static Item dubnium264;
    public static Item dubnium265;
    public static Item dubnium266;
    public static Item dysprosium160;
    public static Item dysprosium161;
    public static Item dysprosium162;
    public static Item dysprosium163;
    public static Item dysprosium164;
    public static Item dysprosium165;
    public static Item einsteinium253;
    public static Item einsteinium254;
    public static Item einsteinium255;
    public static Item electron;
    public static Item electron_capture;
    public static Item erbium166;
    public static Item erbium167;
    public static Item erbium168;
    public static Item erbium169;
    public static Item etain114;
    public static Item etain115;
    public static Item etain116;
    public static Item etain117;
    public static Item etain118;
    public static Item etain119;
    public static Item etain120;
    public static Item etain121;
    public static Item europium151;
    public static Item europium152;
    public static Item fer56;
    public static Item fer57;
    public static Item fer58;
    public static Item fer59;
    public static Item fermium255;
    public static Item flerovium288;
    public static Item flerovium289;
    public static Item fluor19;
    public static Item fluor20;
    public static Item francium221;
    public static Item francium222;
    public static Item gadolinium152;
    public static Item gadolinium153;
    public static Item gadolinium154;
    public static Item gadolinium155;
    public static Item gadolinium156;
    public static Item gadolinium157;
    public static Item gadolinium158;
    public static Item gadolinium159;
    public static Item gallium69;
    public static Item gallium70;
    public static Item gamma_ray;
    public static Item germanium70;
    public static Item germanium71;
    public static Item germanium72;
    public static Item germanium73;
    public static Item germanium74;
    public static Item germanium75;
    public static Item hafnium176;
    public static Item hafnium177;
    public static Item hafnium178;
    public static Item hafnium179;
    public static Item hafnium180;
    public static Item hafnium181;
    public static Item hassium273;
    public static Item hassium275;
    public static Item helium3;
    public static Item helium4;
    public static Item helium5;
    public static Item helium6;
    public static Item holmium165;
    public static Item holmium166;
    public static Item hydrogene1;
    public static Item hydrogene2;
    public static Item hydrogene3;
    public static Item indium113;
    public static Item indium114;
    public static Item iode127;
    public static Item iode128;
    public static Item iridium191;
    public static Item iridium192;
    public static Item it;
    public static Item krypton80;
    public static Item krypton81;
    public static Item krypton82;
    public static Item krypton83;
    public static Item krypton84;
    public static Item krypton85;
    public static Item lanthane139;
    public static Item lanthane140;
    public static Item lawrencium260;
    public static Item lithium6;
    public static Item lithium7;
    public static Item lithium8;
    public static Item lithium9;
    public static Item livermorium291;
    public static Item livermorium292;
    public static Item lutecium175;
    public static Item lutecium176;
    public static Item magnesium24;
    public static Item magnesium25;
    public static Item magnesium26;
    public static Item magnesium27;
    public static Item manganese55;
    public static Item manganese56;
    public static Item meitnerium276;
    public static Item mendelevium255;
    public static Item mendelevium256;
    public static Item mendelevium257;
    public static Item mendelevium258;
    public static Item mercure198;
    public static Item mercure199;
    public static Item mercure200;
    public static Item mercure201;
    public static Item mercure202;
    public static Item mercure203;
    public static Item molybdene94;
    public static Item molybdene95;
    public static Item molybdene96;
    public static Item molybdene97;
    public static Item molybdene98;
    public static Item molybdene99;
    public static Item moscovium290;
    public static Item neodyme142;
    public static Item neodyme143;
    public static Item neodyme144;
    public static Item neodyme145;
    public static Item neodyme146;
    public static Item neodyme147;
    public static Item neon20;
    public static Item neon21;
    public static Item neon22;
    public static Item neon23;
    public static Item neptunium237;
    public static Item neptunium238;
    public static Item neutron;
    public static Item nickel60;
    public static Item nickel61;
    public static Item nickel62;
    public static Item nickel63;
    public static Item nihonium285;
    public static Item nihonium287;
    public static Item niobium93m;
    public static Item niobium93;
    public static Item niobium94;
    public static Item nobelium258;
    public static Item nobelium259;
    public static Item obamium;
    public static Item oganesson294;
    public static Item oganesson295;
    public static Item or197;
    public static Item or198;
    public static Item osmium186;
    public static Item osmium187;
    public static Item osmium188;
    public static Item osmium189;
    public static Item osmium190;
    public static Item osmium191;
    public static Item oxygene16;
    public static Item oxygene17;
    public static Item oxygene18;
    public static Item oxygene19;
    public static Item palladium104;
    public static Item palladium105;
    public static Item palladium106;
    public static Item palladium107;
    public static Item phosphore31;
    public static Item phosphore32;
    public static Item platine192;
    public static Item platine193;
    public static Item platine194;
    public static Item platine195;
    public static Item platine196;
    public static Item platine197;
    public static Item plomb204;
    public static Item plomb205;
    public static Item plomb206;
    public static Item plomb207;
    public static Item plomb208;
    public static Item plomb209;
    public static Item plutonium238;
    public static Item plutonium239;
    public static Item plutonium240;
    public static Item plutonium241;
    public static Item polonium210;
    public static Item polonium211;
    public static Item polonium212;
    public static Item polonium213;
    public static Item polonium214;
    public static Item polonium215;
    public static Item polonium216;
    public static Item polonium217;
    public static Item polonium218;
    public static Item polonium219;
    public static Item potassium39;
    public static Item potassium40;
    public static Item praseodyme141;
    public static Item praseodyme142;
    public static Item promethium147;
    public static Item protactinium231;
    public static Item protactinium232;
    public static Item proton;
    public static Item radium222;
    public static Item radium223;
    public static Item radium224;
    public static Item radium225;
    public static Item radon220;
    public static Item radon221;
    public static Item rhenium185;
    public static Item rhenium186;
    public static Item rhodium103;
    public static Item rhodium104;
    public static Item roentgenium282;
    public static Item rubidium85;
    public static Item rubidium86;
    public static Item ruthenium99;
    public static Item ruthenium100;
    public static Item ruthenium101;
    public static Item ruthenium102;
    public static Item ruthenium103;
    public static Item rutherfordium261;
    public static Item samarium147;
    public static Item samarium148;
    public static Item samarium149;
    public static Item samarium150;
    public static Item samarium151;
    public static Item scandium45;
    public static Item scandium46;
    public static Item seaborgium267;
    public static Item seaborgium269;
    public static Item seaborgium271;
    public static Item selenium76;
    public static Item selenium77;
    public static Item selenium78;
    public static Item selenium79;
    public static Item silicium28;
    public static Item silicium29;
    public static Item silicium30;
    public static Item silicium31;
    public static Item sodium23;
    public static Item sodium24;
    public static Item soufre32;
    public static Item soufre33;
    public static Item soufre34;
    public static Item soufre35;
    public static Item strontium86;
    public static Item strontium87;
    public static Item strontium88;
    public static Item strontium89;
    public static Item tantale181;
    public static Item tantale182;
    public static Item technetium99m;
    public static Item technetium99;
    public static Item tellure122;
    public static Item tellure123;
    public static Item tellure124;
    public static Item tellure125;
    public static Item tellure126;
    public static Item tellure127;
    public static Item tennesse293;
    public static Item terbium159;
    public static Item terbium160;
    public static Item thallium203;
    public static Item thallium204;
    public static Item thorium226;
    public static Item thorium227;
    public static Item thorium228;
    public static Item thorium229;
    public static Item thorium230;
    public static Item thorium231;
    public static Item thulium169;
    public static Item thulium170;
    public static Item titane46;
    public static Item titane47;
    public static Item titane48;
    public static Item titane49;
    public static Item titane50;
    public static Item titane51;
    public static Item tungstene182;
    public static Item tungstene183;
    public static Item tungstene184;
    public static Item tungstene185;
    public static Item uranium232;
    public static Item uranium233;
    public static Item uranium234;
    public static Item uranium235;
    public static Item uranium236;
    public static Item uranium237;
    public static Item vanadium51;
    public static Item vanadium52;
    public static Item xenon128;
    public static Item xenon129;
    public static Item xenon130;
    public static Item xenon131;
    public static Item xenon132;
    public static Item xenon133;
    public static Item ytterbium170;
    public static Item ytterbium171;
    public static Item ytterbium172;
    public static Item ytterbium173;
    public static Item ytterbium174;
    public static Item ytterbium175;
    public static Item yttrium89;
    public static Item yttrium90;
    public static Item zinc64;
    public static Item zinc65;
    public static Item zinc66;
    public static Item zinc67;
    public static Item zinc68;
    public static Item zinc69;
    public static Item zirconium90;
    public static Item zirconium91;
    public static Item zirconium92;
    public static Item zirconium93;
    public static Item obamium_axe;
    public static Item obamium_hoe;
    public static Item obamium_pickaxe;
    public static Item obamium_shovel;
    public static Item obamium_sword;
    public static Item obamium_helmet;
    public static Item obamium_chestplate;
    public static Item obamium_leggings;
    public static Item obamium_boots;
    public static Item double_obamium_axe;
    public static Item double_obamium_hoe;
    public static Item double_obamium_pickaxe;
    public static Item double_obamium_shovel;
    public static Item double_obamium_sword;
    public static Item double_obamium_helmet;
    public static Item double_obamium_chestplate;
    public static Item double_obamium_leggings;
    public static Item double_obamium_boots;
    public static Item triple_obamium_axe;
    public static Item triple_obamium_hoe;
    public static Item triple_obamium_pickaxe;
    public static Item triple_obamium_shovel;
    public static Item triple_obamium_sword;
    public static Item triple_obamium_helmet;
    public static Item triple_obamium_chestplate;
    public static Item triple_obamium_leggings;
    public static Item triple_obamium_boots;

    private static void init(){
        items = Lists.newArrayList();
    }
    @SubscribeEvent
    public static void registerItems(RegistryEvent.Register<Item> event){
        init();
        event.getRegistry().registerAll(
            accelerator = new ItemAtomisation("accelerator"),
            actinium225 = new ItemAtomisation("actinium225"),
            actinium226 = new ItemAtomisation("actinium226"),
            aluminium27 = new ItemAtomisation("aluminium27"),
            aluminium28 = new ItemAtomisation("aluminium28"),
            americium241 = new ItemAtomisation("americium241"),
            americium242 = new ItemAtomisation("americium242"),
            antimoine121 = new ItemAtomisation("antimoine121"),
            antimoine122 = new ItemAtomisation("antimoine122"),
            argent107 = new ItemAtomisation("argent107"),
            argent108 = new ItemAtomisation("argent108"),
            argent109 = new ItemAtomisation("argent109"),
            argent110 = new ItemAtomisation("argent110"),
            argon36 = new ItemAtomisation("argon36"),
            argon37 = new ItemAtomisation("argon37"),
            argon38 = new ItemAtomisation("argon38"),
            argon39 = new ItemAtomisation("argon39"),
            arsenic75 = new ItemAtomisation("arsenic75"),
            arsenic76 = new ItemAtomisation("arsenic76"),
            astate219 = new ItemAtomisation("astate219"),
            astate220 = new ItemAtomisation("astate220"),
            azote14 = new ItemAtomisation("azote14"),
            azote15 = new ItemAtomisation("azote15"),
            azote16 = new ItemAtomisation("azote16"),
            baryum134 = new ItemAtomisation("baryum134"),
            baryum135 = new ItemAtomisation("baryum135"),
            baryum136 = new ItemAtomisation("baryum136"),
            baryum137 = new ItemAtomisation("baryum137"),
            baryum138 = new ItemAtomisation("baryum138"),
            baryum139 = new ItemAtomisation("baryum139"),
            berkelium249 = new ItemAtomisation("berkelium249"),
            beryllium9 = new ItemAtomisation("beryllium9"),
            beryllium10 = new ItemAtomisation("beryllium10"),
            beta_minus = new ItemAtomisation("beta_minus"),
            bismuth209 = new ItemAtomisation("bismuth209"),
            bismuth210 = new ItemAtomisation("bismuth210"),
            bohrium272 = new ItemAtomisation("bohrium272"),
            bore10 = new ItemAtomisation("bore10"),
            bore11 = new ItemAtomisation("bore11"),
            bore12 = new ItemAtomisation("bore12"),
            brome79 = new ItemAtomisation("brome79"),
            brome80 = new ItemAtomisation("brome80"),
            cadmium108 = new ItemAtomisation("cadmium108"),
            cadmium109 = new ItemAtomisation("cadmium109"),
            cadmium110 = new ItemAtomisation("cadmium110"),
            cadmium111 = new ItemAtomisation("cadmium111"),
            cadmium112 = new ItemAtomisation("cadmium112"),
            cadmium113 = new ItemAtomisation("cadmium113"),
            calcium40 = new ItemAtomisation("calcium40"),
            calcium41 = new ItemAtomisation("calcium41"),
            calcium42 = new ItemAtomisation("calcium42"),
            calcium43 = new ItemAtomisation("calcium43"),
            calcium44 = new ItemAtomisation("calcium44"),
            calcium45 = new ItemAtomisation("calcium45"),
            californium249 = new ItemAtomisation("californium249"),
            californium250 = new ItemAtomisation("californium250"),
            californium251 = new ItemAtomisation("californium251"),
            californium252 = new ItemAtomisation("californium252"),
            californium253 = new ItemAtomisation("californium253"),
            carbone12 = new ItemAtomisation("carbone12"),
            carbone13 = new ItemAtomisation("carbone13"),
            carbone14 = new ItemAtomisation("carbone14"),
            cerium140 = new ItemAtomisation("cerium140"),
            cerium141 = new ItemAtomisation("cerium141"),
            cesium133 = new ItemAtomisation("cesium133"),
            cesium134 = new ItemAtomisation("cesium134"),
            chlore35 = new ItemAtomisation("chlore35"),
            chlore36 = new ItemAtomisation("chlore36"),
            chrome52 = new ItemAtomisation("chrome52"),
            chrome53 = new ItemAtomisation("chrome53"),
            chrome54 = new ItemAtomisation("chrome54"),
            chrome55 = new ItemAtomisation("chrome55"),
            cobalt59 = new ItemAtomisation("cobalt59"),
            cobalt60 = new ItemAtomisation("cobalt60"),
            copernicium283 = new ItemAtomisation("copernicium283"),
            copernicium284 = new ItemAtomisation("copernicium284"),
            cuivre63 = new ItemAtomisation("cuivre63"),
            cuivre64 = new ItemAtomisation("cuivre64"),
            curium242 = new ItemAtomisation("curium242"),
            curium243 = new ItemAtomisation("curium243"),
            curium244 = new ItemAtomisation("curium244"),
            curium245 = new ItemAtomisation("curium245"),
            curium246 = new ItemAtomisation("curium246"),
            curium247 = new ItemAtomisation("curium247"),
            curium248 = new ItemAtomisation("curium248"),
            curium249 = new ItemAtomisation("curium249"),
            darmstadtium277 = new ItemAtomisation("darmstadtium277"),
            darmstadtium279 = new ItemAtomisation("darmstadtium279"),
            darmstadtium281 = new ItemAtomisation("darmstadtium281"),
            disposable_fusionner = new ItemAtomisation("disposable_fusionner"),
            dubnium262 = new ItemAtomisation("dubnium262"),
            dubnium263 = new ItemAtomisation("dubnium263"),
            dubnium264 = new ItemAtomisation("dubnium264"),
            dubnium265 = new ItemAtomisation("dubnium265"),
            dubnium266 = new ItemAtomisation("dubnium266"),
            dysprosium160 = new ItemAtomisation("dysprosium160"),
            dysprosium161 = new ItemAtomisation("dysprosium161"),
            dysprosium162 = new ItemAtomisation("dysprosium162"),
            dysprosium163 = new ItemAtomisation("dysprosium163"),
            dysprosium164 = new ItemAtomisation("dysprosium164"),
            dysprosium165 = new ItemAtomisation("dysprosium165"),
            einsteinium253 = new ItemAtomisation("einsteinium253"),
            einsteinium254 = new ItemAtomisation("einsteinium254"),
            einsteinium255 = new ItemAtomisation("einsteinium255"),
            electron = new ItemAtomisation("electron"),
            electron_capture = new ItemAtomisation("electron_capture"),
            erbium166 = new ItemAtomisation("erbium166"),
            erbium167 = new ItemAtomisation("erbium167"),
            erbium168 = new ItemAtomisation("erbium168"),
            erbium169 = new ItemAtomisation("erbium169"),
            etain114 = new ItemAtomisation("etain114"),
            etain115 = new ItemAtomisation("etain115"),
            etain116 = new ItemAtomisation("etain116"),
            etain117 = new ItemAtomisation("etain117"),
            etain118 = new ItemAtomisation("etain118"),
            etain119 = new ItemAtomisation("etain119"),
            etain120 = new ItemAtomisation("etain120"),
            etain121 = new ItemAtomisation("etain121"),
            europium151 = new ItemAtomisation("europium151"),
            europium152 = new ItemAtomisation("europium152"),
            fer56 = new ItemAtomisation("fer56"),
            fer57 = new ItemAtomisation("fer57"),
            fer58 = new ItemAtomisation("fer58"),
            fer59 = new ItemAtomisation("fer59"),
            fermium255 = new ItemAtomisation("fermium255"),
            flerovium288 = new ItemAtomisation("flerovium288"),
            flerovium289 = new ItemAtomisation("flerovium289"),
            fluor19 = new ItemAtomisation("fluor19"),
            fluor20 = new ItemAtomisation("fluor20"),
            francium221 = new ItemAtomisation("francium221"),
            francium222 = new ItemAtomisation("francium222"),
            gadolinium152 = new ItemAtomisation("gadolinium152"),
            gadolinium153 = new ItemAtomisation("gadolinium153"),
            gadolinium154 = new ItemAtomisation("gadolinium154"),
            gadolinium155 = new ItemAtomisation("gadolinium155"),
            gadolinium156 = new ItemAtomisation("gadolinium156"),
            gadolinium157 = new ItemAtomisation("gadolinium157"),
            gadolinium158 = new ItemAtomisation("gadolinium158"),
            gadolinium159 = new ItemAtomisation("gadolinium159"),
            gallium69 = new ItemAtomisation("gallium69"),
            gallium70 = new ItemAtomisation("gallium70"),
            gamma_ray = new ItemAtomisation("gamma_ray"),
            germanium70 = new ItemAtomisation("germanium70"),
            germanium71 = new ItemAtomisation("germanium71"),
            germanium72 = new ItemAtomisation("germanium72"),
            germanium73 = new ItemAtomisation("germanium73"),
            germanium74 = new ItemAtomisation("germanium74"),
            germanium75 = new ItemAtomisation("germanium75"),
            hafnium176 = new ItemAtomisation("hafnium176"),
            hafnium177 = new ItemAtomisation("hafnium177"),
            hafnium178 = new ItemAtomisation("hafnium178"),
            hafnium179 = new ItemAtomisation("hafnium179"),
            hafnium180 = new ItemAtomisation("hafnium180"),
            hafnium181 = new ItemAtomisation("hafnium181"),
            hassium273 = new ItemAtomisation("hassium273"),
            hassium275 = new ItemAtomisation("hassium275"),
            helium3 = new ItemAtomisation("helium3"),
            helium4 = new ItemAtomisation("helium4"),
            helium5 = new ItemAtomisation("helium5"),
            helium6 = new ItemAtomisation("helium6"),
            holmium165 = new ItemAtomisation("holmium165"),
            holmium166 = new ItemAtomisation("holmium166"),
            indium113 = new ItemAtomisation("indium113"),
            indium114 = new ItemAtomisation("indium114"),
            iode127 = new ItemAtomisation("iode127"),
            iode128 = new ItemAtomisation("iode128"),
            iridium191 = new ItemAtomisation("iridium191"),
            iridium192 = new ItemAtomisation("iridium192"),
            it = new ItemAtomisation("it"),
            hydrogene1 = new ItemAtomisation("hydrogene1"),
            hydrogene2 = new ItemAtomisation("hydrogene2"),
            hydrogene3 = new ItemAtomisation("hydrogene3"),
            krypton80 = new ItemAtomisation("krypton80"),
            krypton81 = new ItemAtomisation("krypton81"),
            krypton82 = new ItemAtomisation("krypton82"),
            krypton83 = new ItemAtomisation("krypton83"),
            krypton84 = new ItemAtomisation("krypton84"),
            krypton85 = new ItemAtomisation("krypton85"),
            lanthane139 = new ItemAtomisation("lanthane139"),
            lanthane140 = new ItemAtomisation("lanthane140"),
            lawrencium260 = new ItemAtomisation("lawrencium260"),
            lithium6 = new ItemAtomisation("lithium6"),
            lithium7 = new ItemAtomisation("lithium7"),
            lithium8 = new ItemAtomisation("lithium8"),
            lithium9 = new ItemAtomisation("lithium9"),
            livermorium291 = new ItemAtomisation("livermorium291"),
            livermorium292 = new ItemAtomisation("livermorium292"),
            lutecium175 = new ItemAtomisation("lutecium175"),
            lutecium176 = new ItemAtomisation("lutecium176"),
            magnesium24 = new ItemAtomisation("magnesium24"),
            magnesium25 = new ItemAtomisation("magnesium25"),
            magnesium26 = new ItemAtomisation("magnesium26"),
            magnesium27 = new ItemAtomisation("magnesium27"),
            manganese55 = new ItemAtomisation("manganese55"),
            manganese56 = new ItemAtomisation("manganese56"),
            meitnerium276 = new ItemAtomisation("meitnerium276"),
            mendelevium255 = new ItemAtomisation("mendelevium255"),
            mendelevium256 = new ItemAtomisation("mendelevium256"),
            mendelevium257 = new ItemAtomisation("mendelevium257"),
            mendelevium258 = new ItemAtomisation("mendelevium258"),
            mercure198 = new ItemAtomisation("mercure198"),
            mercure199 = new ItemAtomisation("mercure199"),
            mercure200 = new ItemAtomisation("mercure200"),
            mercure201 = new ItemAtomisation("mercure201"),
            mercure202 = new ItemAtomisation("mercure202"),
            mercure203 = new ItemAtomisation("mercure203"),
            molybdene94 = new ItemAtomisation("molybdene94"),
            molybdene95 = new ItemAtomisation("molybdene95"),
            molybdene96 = new ItemAtomisation("molybdene96"),
            molybdene97 = new ItemAtomisation("molybdene97"),
            molybdene98 = new ItemAtomisation("molybdene98"),
            molybdene99 = new ItemAtomisation("molybdene99"),
            moscovium290 = new ItemAtomisation("moscovium290"),
            neodyme142 = new ItemAtomisation("neodyme142"),
            neodyme143 = new ItemAtomisation("neodyme143"),
            neodyme144 = new ItemAtomisation("neodyme144"),
            neodyme145 = new ItemAtomisation("neodyme145"),
            neodyme146 = new ItemAtomisation("neodyme146"),
            neodyme147 = new ItemAtomisation("neodyme147"),
            neon20 = new ItemAtomisation("neon20"),
            neon21 = new ItemAtomisation("neon21"),
            neon22 = new ItemAtomisation("neon22"),
            neon23 = new ItemAtomisation("neon23"),
            neptunium237 = new ItemAtomisation("neptunium237"),
            neptunium238 = new ItemAtomisation("neptunium238"),
            neutron = new ItemAtomisation("neutron"),
            nickel60 = new ItemAtomisation("nickel60"),
            nickel61 = new ItemAtomisation("nickel61"),
            nickel62 = new ItemAtomisation("nickel62"),
            nickel63 = new ItemAtomisation("nickel63"),
            nihonium285 = new ItemAtomisation("nihonium285"),
            nihonium287 = new ItemAtomisation("nihonium287"),
            niobium93m = new ItemAtomisation("niobium93m"),
            niobium93 = new ItemAtomisation("niobium93"),
            niobium94 = new ItemAtomisation("niobium94"),
            nobelium258 = new ItemAtomisation("nobelium258"),
            nobelium259 = new ItemAtomisation("nobelium259"),
            obamium = new ItemAtomisation("obamium"),
            oganesson294 = new ItemAtomisation("oganesson294"),
            oganesson295 = new ItemAtomisation("oganesson295"),
            or197 = new ItemAtomisation("or197"),
            or198 = new ItemAtomisation("or198"),
            osmium186 = new ItemAtomisation("osmium186"),
            osmium187 = new ItemAtomisation("osmium187"),
            osmium188 = new ItemAtomisation("osmium188"),
            osmium189 = new ItemAtomisation("osmium189"),
            osmium190 = new ItemAtomisation("osmium190"),
            osmium191 = new ItemAtomisation("osmium191"),
            oxygene16 = new ItemAtomisation("oxygene16"),
            oxygene17 = new ItemAtomisation("oxygene17"),
            oxygene18 = new ItemAtomisation("oxygene18"),
            oxygene19 = new ItemAtomisation("oxygene19"),
            palladium104 = new ItemAtomisation("palladium104"),
            palladium105 = new ItemAtomisation("palladium105"),
            palladium106 = new ItemAtomisation("palladium106"),
            palladium107 = new ItemAtomisation("palladium107"),
            phosphore31 = new ItemAtomisation("phosphore31"),
            phosphore32 = new ItemAtomisation("phosphore32"),
            platine192 = new ItemAtomisation("platine192"),
            platine193 = new ItemAtomisation("platine193"),
            platine194 = new ItemAtomisation("platine194"),
            platine195 = new ItemAtomisation("platine195"),
            platine196 = new ItemAtomisation("platine196"),
            platine197 = new ItemAtomisation("platine197"),
            plomb204 = new ItemAtomisation("plomb204"),
            plomb205 = new ItemAtomisation("plomb205"),
            plomb206 = new ItemAtomisation("plomb206"),
            plomb207 = new ItemAtomisation("plomb207"),
            plomb208 = new ItemAtomisation("plomb208"),
            plomb209 = new ItemAtomisation("plomb209"),
            plutonium238 = new ItemAtomisation("plutonium238"),
            plutonium239 = new ItemAtomisation("plutonium239"),
            plutonium240 = new ItemAtomisation("plutonium240"),
            plutonium241 = new ItemAtomisation("plutonium241"),
            polonium210 = new ItemAtomisation("polonium210"),
            polonium211 = new ItemAtomisation("polonium211"),
            polonium212 = new ItemAtomisation("polonium212"),
            polonium213 = new ItemAtomisation("polonium213"),
            polonium214 = new ItemAtomisation("polonium214"),
            polonium215 = new ItemAtomisation("polonium215"),
            polonium216 = new ItemAtomisation("polonium216"),
            polonium217 = new ItemAtomisation("polonium217"),
            polonium218 = new ItemAtomisation("polonium218"),
            polonium219 = new ItemAtomisation("polonium219"),
            potassium39 = new ItemAtomisation("potassium39"),
            potassium40 = new ItemAtomisation("potassium40"),
            praseodyme141 = new ItemAtomisation("praseodyme141"),
            praseodyme142 = new ItemAtomisation("praseodyme142"),
            promethium147 = new ItemAtomisation("promethium147"),
            protactinium231 = new ItemAtomisation("protactinium231"),
            protactinium232 = new ItemAtomisation("protactinium232"),
            proton = new ItemAtomisation("proton"),
            radium222 = new ItemAtomisation("radium222"),
            radium223 = new ItemAtomisation("radium223"),
            radium224 = new ItemAtomisation("radium224"),
            radium225 = new ItemAtomisation("radium225"),
            radon220 = new ItemAtomisation("radon220"),
            radon221 = new ItemAtomisation("radon221"),
            rhenium185 = new ItemAtomisation("rhenium185"),
            rhenium186 = new ItemAtomisation("rhenium186"),
            rhodium103 = new ItemAtomisation("rhodium103"),
            rhodium104 = new ItemAtomisation("rhodium104"),
            roentgenium282 = new ItemAtomisation("roentgenium282"),
            rubidium85 = new ItemAtomisation("rubidium85"),
            rubidium86 = new ItemAtomisation("rubidium86"),
            ruthenium99 = new ItemAtomisation("ruthenium99"),
            ruthenium100 = new ItemAtomisation("ruthenium100"),
            ruthenium101 = new ItemAtomisation("ruthenium101"),
            ruthenium102 = new ItemAtomisation("ruthenium102"),
            ruthenium103 = new ItemAtomisation("ruthenium103"),
            rutherfordium261 = new ItemAtomisation("rutherfordium261"),
            samarium147 = new ItemAtomisation("samarium147"),
            samarium148 = new ItemAtomisation("samarium148"),
            samarium149 = new ItemAtomisation("samarium149"),
            samarium150 = new ItemAtomisation("samarium150"),
            samarium151 = new ItemAtomisation("samarium151"),
            scandium45 = new ItemAtomisation("scandium45"),
            scandium46 = new ItemAtomisation("scandium46"),
            seaborgium267 = new ItemAtomisation("seaborgium267"),
            seaborgium269 = new ItemAtomisation("seaborgium269"),
            seaborgium271 = new ItemAtomisation("seaborgium271"),
            selenium76 = new ItemAtomisation("selenium76"),
            selenium77 = new ItemAtomisation("selenium77"),
            selenium78 = new ItemAtomisation("selenium78"),
            selenium79 = new ItemAtomisation("selenium79"),
            silicium28 = new ItemAtomisation("silicium28"),
            silicium29 = new ItemAtomisation("silicium29"),
            silicium30 = new ItemAtomisation("silicium30"),
            silicium31 = new ItemAtomisation("silicium31"),
            sodium23 = new ItemAtomisation("sodium23"),
            sodium24 = new ItemAtomisation("sodium24"),
            soufre32 = new ItemAtomisation("soufre32"),
            soufre33 = new ItemAtomisation("soufre33"),
            soufre34 = new ItemAtomisation("soufre34"),
            soufre35 = new ItemAtomisation("soufre35"),
            strontium86 = new ItemAtomisation("strontium86"),
            strontium87 = new ItemAtomisation("strontium87"),
            strontium88 = new ItemAtomisation("strontium88"),
            strontium89 = new ItemAtomisation("strontium89"),
            tantale181 = new ItemAtomisation("tantale181"),
            tantale182 = new ItemAtomisation("tantale182"),
            technetium99m = new ItemAtomisation("technetium99m"),
            technetium99 = new ItemAtomisation("technetium99"),
            tellure122 = new ItemAtomisation("tellure122"),
            tellure123 = new ItemAtomisation("tellure123"),
            tellure124 = new ItemAtomisation("tellure124"),
            tellure125 = new ItemAtomisation("tellure125"),
            tellure126 = new ItemAtomisation("tellure126"),
            tellure127 = new ItemAtomisation("tellure127"),
            tennesse293 = new ItemAtomisation("tennesse293"),
            terbium159 = new ItemAtomisation("terbium159"),
            terbium160 = new ItemAtomisation("terbium160"),
            thallium203 = new ItemAtomisation("thallium203"),
            thallium204 = new ItemAtomisation("thallium204"),
            thorium226 = new ItemAtomisation("thorium226"),
            thorium227 = new ItemAtomisation("thorium227"),
            thorium228 = new ItemAtomisation("thorium228"),
            thorium229 = new ItemAtomisation("thorium229"),
            thorium230 = new ItemAtomisation("thorium230"),
            thorium231 = new ItemAtomisation("thorium231"),
            thulium169 = new ItemAtomisation("thulium169"),
            thulium170 = new ItemAtomisation("thulium170"),
            titane46 = new ItemAtomisation("titane46"),
            titane47 = new ItemAtomisation("titane47"),
            titane48 = new ItemAtomisation("titane48"),
            titane49 = new ItemAtomisation("titane49"),
            titane50 = new ItemAtomisation("titane50"),
            titane51 = new ItemAtomisation("titane51"),
            tungstene182 = new ItemAtomisation("tungstene182"),
            tungstene183 = new ItemAtomisation("tungstene183"),
            tungstene184 = new ItemAtomisation("tungstene184"),
            tungstene185 = new ItemAtomisation("tungstene185"),
            uranium232 = new ItemAtomisation("uranium232"),
            uranium233 = new ItemAtomisation("uranium233"),
            uranium234 = new ItemAtomisation("uranium234"),
            uranium235 = new ItemAtomisation("uranium235"),
            uranium236 = new ItemAtomisation("uranium236"),
            uranium237 = new ItemAtomisation("uranium237"),
            vanadium51 = new ItemAtomisation("vanadium51"),
            vanadium52 = new ItemAtomisation("vanadium52"),
            xenon128 = new ItemAtomisation("xenon128"),
            xenon129 = new ItemAtomisation("xenon129"),
            xenon130 = new ItemAtomisation("xenon130"),
            xenon131 = new ItemAtomisation("xenon131"),
            xenon132 = new ItemAtomisation("xenon132"),
            xenon133 = new ItemAtomisation("xenon133"),
            ytterbium170 = new ItemAtomisation("ytterbium170"),
            ytterbium171 = new ItemAtomisation("ytterbium171"),
            ytterbium172 = new ItemAtomisation("ytterbium172"),
            ytterbium173 = new ItemAtomisation("ytterbium173"),
            ytterbium174 = new ItemAtomisation("ytterbium174"),
            ytterbium175 = new ItemAtomisation("ytterbium175"),
            yttrium89 = new ItemAtomisation("yttrium89"),
            yttrium90 = new ItemAtomisation("yttrium90"),
            zinc64 = new ItemAtomisation("zinc64"),
            zinc65 = new ItemAtomisation("zinc65"),
            zinc66 = new ItemAtomisation("zinc66"),
            zinc67 = new ItemAtomisation("zinc67"),
            zinc68 = new ItemAtomisation("zinc68"),
            zinc69 = new ItemAtomisation("zinc69"),
            zirconium90 = new ItemAtomisation("zirconium90"),
            zirconium91 = new ItemAtomisation("zirconium91"),
            zirconium92 = new ItemAtomisation("zirconium92"),
            zirconium93 = new ItemAtomisation("zirconium93"),
            obamium_axe = new ItemCustomAxe(ToolMaterialList.obamium, 0.0f, -2.5f, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("obamium_axe")),
            obamium_hoe = new HoeItem(ToolMaterialList.obamium,2.0f, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("obamium_hoe")),
            obamium_pickaxe = new ItemCustomPickaxe(ToolMaterialList.obamium, -4,-2.5f, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("obamium_pickaxe")),
            obamium_shovel = new ShovelItem(ToolMaterialList.obamium, -3.0f, -2.5f, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("obamium_shovel")),
            obamium_sword = new SwordItem(ToolMaterialList.obamium, -2, -2.0f, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("obamium_sword")),
            obamium_helmet = new ArmorItem(ToolArmorList.obamium, EquipmentSlotType.HEAD, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("obamium_helmet")),
            obamium_chestplate = new ArmorItem(ToolArmorList.obamium, EquipmentSlotType.CHEST, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("obamium_chestplate")),
            obamium_leggings = new ArmorItem(ToolArmorList.obamium, EquipmentSlotType.LEGS, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("obamium_leggings")),
            obamium_boots = new ArmorItem(ToolArmorList.obamium, EquipmentSlotType.FEET, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("obamium_boots")),
            double_obamium_axe = new ItemCustomAxe(ToolMaterialList2.obamium2, 0.0f, -2.5f, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("double_obamium_axe")),
            double_obamium_hoe = new HoeItem(ToolMaterialList2.obamium2, 2.0f, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("double_obamium_hoe")),
            double_obamium_pickaxe = new ItemCustomPickaxe(ToolMaterialList2.obamium2, -4,-2.5f, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("double_obamium_pickaxe")),
            double_obamium_shovel = new ShovelItem(ToolMaterialList2.obamium2, -3.0f, -2.5f, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("double_obamium_shovel")),
            double_obamium_sword = new SwordItem(ToolMaterialList2.obamium2, -2, -2.0f, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("double_obamium_sword")),
            double_obamium_helmet = new ArmorItem(ToolArmorList2.obamium2, EquipmentSlotType.HEAD, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("double_obamium_helmet")),
            double_obamium_chestplate = new ArmorItem(ToolArmorList2.obamium2, EquipmentSlotType.CHEST, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("double_obamium_chestplate")),
            double_obamium_leggings = new ArmorItem(ToolArmorList2.obamium2, EquipmentSlotType.LEGS, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("double_obamium_leggings")),
            double_obamium_boots = new ArmorItem(ToolArmorList2.obamium2, EquipmentSlotType.FEET, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("double_obamium_boots")),
            triple_obamium_axe = new ItemCustomAxe(ToolMaterialList3.obamium3, 0.0f, -2.5f, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("triple_obamium_axe")),
            triple_obamium_hoe = new HoeItem(ToolMaterialList3.obamium3, 2.0f, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("triple_obamium_hoe")),
            triple_obamium_pickaxe = new ItemCustomPickaxe(ToolMaterialList3.obamium3, -4,-2.5f, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("triple_obamium_pickaxe")),
            triple_obamium_shovel = new ShovelItem(ToolMaterialList3.obamium3, -3.0f, -2.5f, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("triple_obamium_shovel")),
            triple_obamium_sword = new SwordItem(ToolMaterialList3.obamium3, -2, -2.0f, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("triple_obamium_sword")),
            triple_obamium_helmet = new ArmorItem(ToolArmorList3.obamium3, EquipmentSlotType.HEAD, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("triple_obamium_helmet")),
            triple_obamium_chestplate = new ArmorItem(ToolArmorList3.obamium3, EquipmentSlotType.CHEST, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("triple_obamium_chestplate")),
            triple_obamium_leggings = new ArmorItem(ToolArmorList3.obamium3, EquipmentSlotType.LEGS, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("triple_obamium_leggings")),
            triple_obamium_boots = new ArmorItem(ToolArmorList3.obamium3, EquipmentSlotType.FEET, new Item.Properties().group(Atomisation.MFF_GROUP)).setRegistryName(location("triple_obamium_boots"))
                );
    }
    public static ResourceLocation location(String name){
        return new ResourceLocation(Atomisation.MODID, name);
    }
}
